name: 'market_stream'
version: '1.0.0'
config-version: 2

profile: 'market_stream'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  market_stream:
    staging:
      +materialized: view
    marts:
      +materialized: table
